### PR TITLE
quote pr title properly

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix https://github.com/coq/bot/issues/98

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
Cool, thanks!

**Comment by Zimmi48** [comment]
This is the `Filename.quote` from the stdlib though and `Base` deprecates it. Is there a `Base` equivalent?

**Comment by SkySkimmer** [comment]
I don't use Base

**Comment by Zimmi48** [comment]
OK, I've just qualified the `Filename` module with `Stdlib` to disable the warning.

**Pull request merged**
