### PR TITLE
[coq] [doc] Update for new upstream documentation jobs

### PR DESCRIPTION
**Pull request by ejgallego**
This should be merged after #15560

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
Guillaume has pointed out that this will break the CI for other branches. Would it be possible to fall back to the old link if the new doesn't work?

**Comment by Zimmi48** [comment]
This is exactly what I would recommend. Then, this PR could be merged first (like a backward compatible overlay).

**Comment by ejgallego** [comment]
Config like this tho shouldn't live in the source code, maybe the bot could read a `bot-config.json` file from each repos?

[excuse my unfamiliarity with the bot]

**Comment by ejgallego** [comment]
Not sure Ali can push here, as the box is already checked, so closing in favor of #233

**Comment by Zimmi48** [comment]
> Config like this tho shouldn't live in the source code, maybe the bot could read a `bot-config.json` file from each repos?
> 
> [excuse my unfamiliarity with the bot]

We do have a feature for reading a repo-specific configuration file (`coqbot.toml`). It would just need to be extended to handle this specific feature. But that would require designing what this feature means in general (beyond the specific case of Coq's documentation artifacts).

**Pull request closed without merging**
