### PR TITLE
GitHub actions to automate the release and deployment of our Docker images

### PR DESCRIPTION
**Pull request by jtcoolen**
This PR adds two GitHub actions which:

- Build and publish a Docker image to GitHub packages at each new release
- Build and deploy the Docker image to Heroku after a new commit from the master branch

It also updates the documentation to reflect those changes, as well as the nix environment.

### CODE REVIEW

**Comment by jtcoolen** [comment]
Great! I'll take care of this tomorrow.
This PR does enough things already.

**Comment by jtcoolen** [comment]
The quick fix to conform to the new Lwt.async signature breaks the server.

**Comment by Zimmi48** [comment]
OK thanks for letting me know. I've cancelled the deployment process then.

**Comment by jtcoolen** [comment]
The four first commits are fine, you could remove the last four commits.

**Comment by jtcoolen** [comment]
Or rather, I'll open a new issue fixing the error.

**Pull request merged**
