### PR TITLE
Update to mirage-crypto 1.0.0 API

### PR DESCRIPTION
**Pull request by hannesm**
Hey,

I updated the code for mirage-crypto 1.0.0 API changes. I hope this is all that needs changing (I'm not a nix person, so there may be some update needed).

I added a second commit which is an ocamlformat run -- this is run with 0.26.2 and has quite some changes, please let me know whether it should be included or not.

Best,

Hannes

### CODE REVIEW

**Comment by Zimmi48** [comment]
Thanks for these updates!

I will indeed need to update the version of mirage-crypto in nixpkgs to 1.0.0 / 1.1.0 before merging this (unless someone else is already working on this, @vbgl?).

**Comment by vbgl** [comment]
I’ve got a branch of nixpkgs that is ready with the mirage-crypto update. I’ll open a PR asap.

**Comment by vbgl** [comment]
Done. May I hijack this PR to ask if there are any plans to port jackline to mirage-crypto 1.0?

**Comment by hannesm** [comment]
> Done. May I hijack this PR to ask if there are any plans to port jackline to mirage-crypto 1.0?

sure, I'll only need some time to push that through. I wasn't aware that there's such a dependency, but understand (or presume) that for nix it makes sense to only contain a single mirage-crypto...

**Comment by JasonGross** [comment]
> I added a second commit which is an ocamlformat run -- this is run with 0.26.2 and has quite some changes, please let me know whether it should be included or not.

I'm happy to have this, though if we want to bump the version to 0.26.2, please update the line in CONTRIBUTING.md that says 0.15.0 is required to 0.26.2.

**Comment by hannesm** [comment]
@vbgl said:

> Done. May I hijack this PR to ask if there are any plans to port jackline to mirage-crypto 1.0?

That is done. See https://github.com/ocaml/opam-repository/pull/26768 as last dependency and https://github.com/hannesm/jackline/pull/229 (together with https://github.com/hannesm/xmpp/commit/54418f77abf47b175e9c1b68a4f745a12b640d6a).

@JasonGross said:

> I'm happy to have this, though if we want to bump the version to 0.26.2, please update the line in CONTRIBUTING.md that says 0.15.0 is required to 0.26.2.

Done in https://github.com/coq/bot/pull/314/commits/50324a9fdbdd276269d7b094a197d887b16d2d79

**Comment by JasonGross** [comment]
I think if you rebase on current master, the ocamlformat commits will be redundant

**Comment by hannesm** [comment]
> I think if you rebase on current master, the ocamlformat commits will be redundant

done in [9fa2c8e](https://github.com/coq/bot/pull/314/commits/9fa2c8ef8e6e4a33f07459c112f0aeb3b4efec7e)

**Comment by vbgl** [comment]
Thank you Hannes.

**Review by Zimmi48 — APPROVED** [review]
Thanks again!
I have now updated the nixpkgs version to be compatible with this PR.

**Pull request merged**
